### ISSUE TITLE
Request to add Chinese

### ISSUE THREAD

**Issue by Annijang** [Fusion-Flux/Dyeable-Fishing-Lines#2]
Hi, I really like the color of the rod, can I add the corresponding color for Chinese? Switch from English to Chinese.

**Comment by Nordigoistired** [comment]
Why not learn how to do it your self? If you already know the language it would be easier to learn how to add it instead of the dev adding a language the most likely don't know.

**Comment by Annijang** [comment]
> 

Thank you, I didn't know how to set it up before 2022, now I know how it works so I'll add it myself, thanks for reminding me via GitHub, thanks.
